// <auto-generated />
using DatabaseLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseLib.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20210930205851_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DatabaseLib.Armor", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Defense")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("DatabaseLib.Player", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<double>("Attack")
                        .HasColumnType("REAL");

                    b.Property<string>("BootsName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChestPlateName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Defense")
                        .HasColumnType("REAL");

                    b.Property<string>("HelmetName")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hp")
                        .HasColumnType("REAL");

                    b.Property<string>("LeggingsName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lvl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weapon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("BootsName");

                    b.HasIndex("ChestPlateName");

                    b.HasIndex("HelmetName");

                    b.HasIndex("LeggingsName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DatabaseLib.Player", b =>
                {
                    b.HasOne("DatabaseLib.Armor", "Boots")
                        .WithMany()
                        .HasForeignKey("BootsName");

                    b.HasOne("DatabaseLib.Armor", "ChestPlate")
                        .WithMany()
                        .HasForeignKey("ChestPlateName");

                    b.HasOne("DatabaseLib.Armor", "Helmet")
                        .WithMany()
                        .HasForeignKey("HelmetName");

                    b.HasOne("DatabaseLib.Armor", "Leggings")
                        .WithMany()
                        .HasForeignKey("LeggingsName");

                    b.Navigation("Boots");

                    b.Navigation("ChestPlate");

                    b.Navigation("Helmet");

                    b.Navigation("Leggings");
                });
#pragma warning restore 612, 618
        }
    }
}
